import styles from './About.module.css'

export default function Terms() {
  return (
    <main className={styles.page}>
      <div className={styles.container}>

        <div className={styles.hero}>
          <h1>Terms of Service</h1>
          <p>Last updated: April 5, 2026</p>
        </div>

        <div className={styles.section}>
          <h2>Acceptance of terms</h2>
          <p>
            By using CapitolKey, you agree to these Terms of Service and our
            Privacy Policy. If you do not agree, please do not use the app. We
            may update these terms from time to time; continued use after changes
            constitutes acceptance. We will notify users of material changes
            through the app or by email.
          </p>
        </div>

        <div className={styles.section}>
          <h2>Eligibility</h2>
          <div className={styles.neutralBox}>
            <div className={styles.neutralIcon}>&#9432;</div>
            <p>
              You must be at least <strong>13 years of age</strong> to use
              CapitolKey. By using the app, you represent and warrant that you
              are 13 or older. If you are under 18, you represent that you have
              your parent's or legal guardian's permission to use the service.
              We do not knowingly collect information from anyone under 13, in
              compliance with the Children's Online Privacy Protection Act
              (COPPA).
            </p>
          </div>
        </div>

        <div className={styles.section}>
          <h2>What CapitolKey provides</h2>
          <p>
            CapitolKey is a nonpartisan civic education tool that displays
            publicly available federal and state legislation and generates
            AI-powered plain-language explanations personalized to your profile.
            The app is designed for informational and educational purposes only.
          </p>
        </div>

        <div className={styles.section}>
          <h2>Not legal or political advice</h2>
          <div className={styles.neutralBox}>
            <div className={styles.neutralIcon}>&#9878;</div>
            <p>
              CapitolKey does not provide legal, political, or professional
              advice. AI-generated explanations are approximations and may not
              reflect every nuance of a bill. Always consult official sources or
              qualified professionals for decisions based on legislation.
            </p>
          </div>
        </div>

        <div className={styles.section}>
          <h2>AI-generated content disclaimer</h2>
          <p>
            Personalized bill explanations are generated by artificial
            intelligence (Anthropic's Claude). While we strive for accuracy,
            AI-generated content may contain errors, omissions, or
            oversimplifications. CapitolKey does not guarantee the accuracy,
            completeness, or timeliness of any AI-generated content. Users
            should verify important information through official government
            sources.
          </p>
        </div>

        <div className={styles.section}>
          <h2>Accounts and data</h2>
          <p>
            You may use CapitolKey without an account. If you create one, you
            are responsible for maintaining the security of your login
            credentials and for all activity that occurs under your account. You
            agree to notify us immediately of any unauthorized use. We may
            suspend or delete accounts that violate these terms or are used for
            abusive purposes.
          </p>
        </div>

        <div className={styles.section}>
          <h2>Acceptable use</h2>
          <p>
            You agree not to use CapitolKey to:
          </p>
          <ul style={{ color: 'var(--text-secondary)', lineHeight: 1.75, paddingLeft: '1.25rem', marginTop: '0.5rem' }}>
            <li>Abuse, overload, or interfere with the service or its infrastructure</li>
            <li>Scrape, crawl, or extract data in bulk by automated means</li>
            <li>Misrepresent AI-generated content as official government communication</li>
            <li>Use the service for any unlawful purpose</li>
            <li>Attempt to gain unauthorized access to other users' accounts or data</li>
            <li>Distribute malware, spam, or other harmful content through the service</li>
            <li>Use the service to harass, defame, or threaten others</li>
          </ul>
        </div>

        <div className={styles.section}>
          <h2>Intellectual property</h2>
          <p>
            Legislation data is sourced from Congress.gov and LegiScan and is in
            the public domain. AI-generated explanations are provided for your
            personal, non-commercial use only. The CapitolKey name, logo, app
            design, and source code are the property of CapitolKey and are
            protected by applicable copyright and trademark laws. Unauthorized
            copying, reproduction, or redistribution is prohibited.
          </p>
        </div>

        <div className={styles.section}>
          <h2>Service availability</h2>
          <p>
            We strive to keep CapitolKey available at all times, but we do not
            guarantee uninterrupted access. The service may be temporarily
            unavailable due to maintenance, updates, or circumstances beyond our
            control. We reserve the right to modify, suspend, or discontinue the
            service (or any part of it) at any time with or without notice.
          </p>
        </div>

        <div className={styles.section}>
          <h2>Limitation of liability</h2>
          <p>
            To the fullest extent permitted by law, CapitolKey and its creators
            shall not be liable for any indirect, incidental, special,
            consequential, or punitive damages, or any loss of profits or
            revenues, whether incurred directly or indirectly, arising from:
          </p>
          <ul style={{ color: 'var(--text-secondary)', lineHeight: 1.75, paddingLeft: '1.25rem', marginTop: '0.5rem' }}>
            <li>Your use of or inability to use the service</li>
            <li>Any inaccuracies in AI-generated content</li>
            <li>Unauthorized access to your account or data</li>
            <li>Service interruptions or data loss</li>
            <li>Any third-party content or services accessed through CapitolKey</li>
          </ul>
          <p>
            The service is provided "as is" and "as available" without warranties
            of any kind, whether express or implied, including but not limited to
            implied warranties of merchantability, fitness for a particular
            purpose, and non-infringement.
          </p>
        </div>

        <div className={styles.section}>
          <h2>Indemnification</h2>
          <p>
            You agree to indemnify and hold harmless CapitolKey and its creators
            from any claims, damages, losses, or expenses (including reasonable
            attorneys' fees) arising from your use of the service, your violation
            of these terms, or your violation of any rights of a third party.
          </p>
        </div>

        <div className={styles.section}>
          <h2>Governing law</h2>
          <p>
            These terms shall be governed by and construed in accordance with the
            laws of the United States and the State of Connecticut, without regard
            to its conflict of law provisions. Any disputes arising from these
            terms or your use of CapitolKey shall be resolved in the courts of
            the State of Connecticut.
          </p>
        </div>

        <div className={styles.section}>
          <h2>Severability</h2>
          <p>
            If any provision of these Terms is found to be unenforceable or
            invalid, that provision shall be limited or eliminated to the minimum
            extent necessary so that these Terms shall otherwise remain in full
            force and effect.
          </p>
        </div>

        <div className={styles.section}>
          <h2>Contact</h2>
          <p>
            For questions about these terms, email us at{' '}
            <a href="mailto:capitolkeyapp@gmail.com" style={{ color: 'var(--amber)' }}>
              capitolkeyapp@gmail.com
            </a>.
          </p>
        </div>

      </div>
    </main>
  )
}
